Market.create(name:"Country Market & Craft Fair at Waimanalo Homestead Community Center", address:"1330 Kalanianaole Hwy. HI")
Market.create(name:"Halawa District Park (People's Open Market)", address:"99-795 Iwaiwa Street HI")
Market.create(name:"Kahaluu Farmers' Market at Windward Baptist Church", address:"47-528A Kamehameha Hwy. HI")
Market.create(name:"Kailua Elementary School", address:"315 Kuulei Road HI")
Market.create(name:"Hawaiian Homestead Farmers’ Market at Kuhio Hale Building", address:"64-759 Kahilu Road, Waimea")
Market.create(name:"Hilo Coffee Mill 'Market @ The Mill'", address:"17-995 Volcano Rd")
Market.create(name:"Kekela Farm", address:"64-604 Mana Road")
Market.create(name:"Kona Farmers’ Market", address:"74-5465 Kamakaeha Avenue")
Market.create(name:"Volcano Farmers’ Market", address:"1000 Wright Road Cooper Center, Volcano")
Market.create(name:"Kapaa New Town Park (Sunshine Markets)", address:"Kahau Road, Kapaa")
Market.create(name:"Kekaha Neighborhood Center (Sunshine Markets)", address:"Elepaio Road, Kekaha")
Market.create(name:"Koloa Ball Park (Knudsen) (Sunshine Markets)", address:"Maluhia Road")
Market.create(name:"Country Market & Craft Fair", address:"1330 Kalanianaole Hwy.")
Market.create(name:"Davies Pacific Center", address:"841 Bishop Street")
Market.create(name:"Dole Cannery", address:"650 Iwilei Road")
Market.create(name:"Waikoloa Village Farmers Market", address:"68-3625 Paniolo Ave. Waikoloa")
Market.create(name:"Waipahu District Park (People's Open Market)", address:"94-230 Paiwa Stree Waipahu, HI")
Market.create(name:"Makeke Kapolei", address:"Kapolei, HI")
Market.create(name:"The Maui's Fresh Produce Farmer's Market at Queen Ka'ahumanu Shopping Center", address:"275 W. Ka&rsquo;ahumanu Ave Kahului, HI 96732")
Market.create(name:"Pokai Bay Beach Park (People's Open Market)", address:"85-037 Pokai Bay Road Waianae, HI")
Market.create(name:"Dole Cannery", address:"650 Iwilei Road Honolulu, HI")
Market.create(name:"Kalaheo Neighborhood Center (Sunshine Markets)", address:"Papalina Road Kalaheo")
Market.create(name:"Makawao Farmers' Market", address:"200 Olinda Rd. Makawao, HI 96768")
Market.create(name:"Kukui Grove Shopping Center", address:"Lihue")
Market.create(name:"Farmers' Market of Maui-Kihei", address:"61 South Kihei Road Kihei, HI 96753-8801")
Market.create(name:"Alii Garden Market Place", address:"75-6129 Alii Drive Kailua-Kona")
Market.create(name:"Maui Mall Farmers' Market & Craft Fair", address:"70 East Kaahumanu Ave Kahului, HI 96732")
Market.create(name:"Benjamin Parker Elementary School", address:"45-259 Waikalua Road Kaneohe, HI")
Market.create(name:"Hawaii Kai Farmers' Market at Kaiser High School", address:"511 Lunalilo Home Road Honolulu, HI")
Market.create(name:"Vidinha Stadium (Sunshine Markets)", address:"Hoolako Road Lihue")
Market.create(name:"Honolulu Farmers' Market at Neal S. Blaisdell Center", address:"777 Ward Ave Honolulu, HI 96814")
Market.create(name:"Kaumualii Street (People's Open Market)", address:"Honolulu, HI")
Market.create(name:"Akebono Farmers’ Market", address:"Pahoa, HI")
Market.create(name:"Royal Kunia Park-n-Ride (People's Open Market)", address:"Waipahu, HI")
Market.create(name:"The South Kona Green Market at Amy Greenwell Ethnobotanical Garden field in", address:"Captain Cook")
Market.create(name:"North Shore Country Market at Sunset Beach Elementary School", address:"Haleiwa, HI")
Market.create(name:"Hale'iwa Farmers' Market", address:"HI")
Market.create(name:"Ono Organic Farms Farmers' Market in Hana", address:"149 Hana Highway Hana, HI 96713")
Market.create(name:"Fort Street near Wilcox Park", address:"Honolulu, HI")
Market.create(name:"Salt Lake Municipal Lot (People's Open Market)", address:"5337 Likini Street Honolulu, HI")
Market.create(name:"Queen's Medical Center", address:"1301 Punchbowl Street Honolulu, HI")
Market.create(name:"City Hall Parking Lot Deck (People's Open Market)", address:"Honolulu, HI")
Market.create(name:"Waikiki Farmers' Market", address:"HI")
Market.create(name:"Ewa Beach Community Park (People's Open Market)", address:"91-955 North Road Ewa Beach, HI")
Market.create(name:"Kaneohe District Park (People's Open Market)", address:"45-660 Keaahala Road Kaneohe, HI")
Market.create(name:"Hawaii Kai Park-n-Ride (People's Open Market)", address:"300 Keahole Street, Honolulu Honolulu, HI")
Market.create(name:"Davies Pacific Center", address:"841 Bishop Street Honolulu, HI")
Market.create(name:"Maui Swap Meet at Maui Community College", address:"310 Ka'ahumanu Avenue Kahului, HI 96732")
Market.create(name:"Kaka'ako Makai Community Cultural Marketplace", address:"Honolulu, HI")
Market.create(name:"Kailua District Park (People's Open Market)", address:"21 South Kainalu Drive Kailua, HI")
Market.create(name:"First Insurance Center", address:"1100 Ward Ave Honolulu, HI")
Market.create(name:"Kalihi Valley District Park (People's Open Market)", address:"1911 Kam IV Road Honolulu, HI")
Market.create(name:"City Hall Parking Lot Deck (People's Open Market)", address:"Honolulu, HI")
Market.create(name:"Waianae Farmers' Market (sponsored by Waianae Coast Comprehensive Center)", address:"85-251 Farrington Highway Waianae, HI")
Market.create(name:"Mahiku Farmers' Market at Momilani Community Center", address:"715 Hoomoana St Pearl City, HI 96782")
Market.create(name:"Ewa Beach Elementary School", address:"91-740 Papipi Road Ewa Beach, HI")
Market.create(name:"Mahiku Farmers' Market at International Market Place-Waikiki", address:"Honolulu, HI")
Market.create(name:"King's Village Shopping Center", address:"131 Kaiulani Ave. Honolulu, HI")
Market.create(name:"Lipoa Street Farmers' Market", address:"95 Lipoa Street Kihei, HI 96753")
Market.create(name:"Kalihi Farmers' Market at Kapalama Elementary School", address:"1601 N. School Street Honolulu, HI")
Market.create(name:"The Saturday Farmers' Market at Kapiolani Community College Campus", address:"4303 Diamond Head Road Honolulu, HI 96816")
Market.create(name:"Hali'imaile Farmers' Market at Hali'imaile Town Center", address:"900 Haliimaile Rd Makawao, HI 96768")
Market.create(name:"Makiki District Park (People's Open Market)", address:"1527 Keeaumoku Street Honolulu, HI")
Market.create(name:"The Kailua Thursday Night Farmers Market", address:"Kailua, HI")
Market.create(name:"Waialua Farmers' Market", address:"HI")
Market.create(name:"Nuuanu Farmers Market at Honolulu Central Seventh Day Adventist Church", address:"2313 Nuuanu Avenue Honolulu, HI")
Market.create(name:"The Mililani Sunday Farmers' Market at Mililani High School", address:"95-1200 Meheula Parkway Mililani, HI")
Market.create(name:"Upcountry Farmers' Market at Pukalani Longs Drugs at Kulamalu", address:"55 Kiopaa St Makawao, HI 96768")
Market.create(name:"Mililani District Park (People's Open Market)", address:"94-1150 Lanikuhana Avenue Mililani, HI")
Market.create(name:"Manoa Marketplace", address:"2752 Woodlawn Drive Honolulu, HI 96822")
Market.create(name:"Maui Open Market, Maui Tropical Plantation", address:"1670 HONOAPIILANI HWY Wailuku, HI 96793")
Market.create(name:"Banyan Court Mall (People's Open Market)", address:"800 North King Street Honolulu, HI")
Market.create(name:"Old Stadium Park (People's Open Market)", address:"2237 South King Street Honolulu, HI")
Market.create(name:"Hawaii Kai Towne Center", address:"333 Keahole Street Honolulu, HI 96825")
Market.create(name:"Hana Fresh Market", address:"4590 H&#257;na Highway Hana, HI 96713")
Market.create(name:"Kinoole Farmer's Market", address:"1990 Kinoole Street, Hilo")
Market.create(name:"Ala Moana Farmers' Market", address:"1450 Ala Moana Blvd. Honolulu, HI")
Market.create(name:"Molokai Saturday Market", address:"40 Ala Malama Street Kaunakakai, HI 96748")
Market.create(name:"Waiau District Park (People's Open Market)", address:"Pearl City, HI")
Market.create(name:"Hanalei Saturday Market", address:"Hanalei")
Market.create(name:"Kaka'ako Makai Community Cultural Marketplace", address:"Honolulu, HI")
Market.create(name:"Merchant Street Market", address:"841 Bishop Street Honolulu, HI")
Market.create(name:"Mother Waldron Park (People's Open Market)", address:"525 Coral Street Honolulu, HI")
Market.create(name:"Wahiawa District Park (People's Open Market)", address:"HI")
Market.create(name:"Ewa Beach Community Park (People's Open Market)", address:"91-955 North Road Ewa Beach")
Market.create(name:"Banyan Court Mall (People's Open Market)", address:"800 North King Street Honolulu, HI")
Market.create(name:"Paia’s One Love Farmers Market", address:"381 Baldwin Ave Paia, HI 96799")
Market.create(name:"International Market Place", address:"2330 Kalakaua Avenue Honolulu, HI")
Market.create(name:"Queen Kapiolani Park (People's Open Market)", address:"Honolulu, HI")
Market.create(name:"Kapolei Community Park (People's Open Market)", address:"91-1049 Kamaaha Loop Kapolei, HI")
Market.create(name:"Ward Center", address:"HI")
Market.create(name:"Makiki Local Grown Farmers' Market at St. Clement's Church", address:"1515 Wilder Avenue Honolulu, HI")
Market.create(name:"Waimanalo Beach Park (People's Open Market)", address:"41-741 Kalanianaole Highway Waimanalo, HI")
Market.create(name:"Windward Mall", address:"46-056 Kamehameha Highway Kaneohe, HI")
Market.create(name:"Farmers' Market of Maui-Honokowai", address:"3636 Lower Honoapi&lsquo;ilani Road Lahina, HI 96761")
Market.create(name:"Manoa Valley District Park (People's Open Market)", address:"2721 Kaaipu Avenue Honolulu, HI 96822")
Market.create(name:"Ala Moana Farmers' Market", address:"1450 Ala Moana Blvd. Honolulu, HI")
Market.create(name:"Palolo Valley District Park (People's Open Market)", address:"2007 Palolo Avenue Honolulu, HI 96816")
Market.create(name:"Benjamin Parker Elementary School", address:"45-259 Waikalua Road Kaneohe, HI")
Market.create(name:"Waikele Community Park (People's Open Market)", address:"94-870 Lumiaina Street Waipahu, HI")
